### ISSUE TITLE
Question about the usage of text input

### ISSUE THREAD

**Issue by laoShuaiGe** [wp03052/MATRN#4]
I noticed that texts(index encoding) is passed to the forward function, but not used anywhere. Just curious that, are you going to "ADD" text embedding to the final output?  My guess is that, you probably have tried it out, but got limited performance improvements. I've been thinking about the usage of text embedding for a while, but it's too hard to convince myself to add text embedding to the training pipeline. As in the inference time, no text information will be given. Please correct me if my guess is wrong. Thanks.

**Comment by byeonghu-na** [comment]
That's a good point!
As you mentioned, our model does not use text information for both training and inference, and using the text information in STR model is not trivial approach as your guess.
Actually, we want to use the text information in visual clue masking which is our special strategy to boost STR performance. In this approach, we might not worry about using the text information since masking is not used in inference time.

**Comment by laoShuaiGe** [comment]
It sounds really mind-blowing to me. 
Will you post the code to show your  "special strategy to boost STR" soon?  Can't wait to see the implementation.

**Comment by byeonghu-na** [comment]
Oh, sorry for the confusion. Actually, I meant that the visual clue masking is our special strategy to boost STR in our model, MATRN. But, in now, we just pick a position randomly and mask the top-K visual features relevant to the chosen position.
I want to say that the position picking process might be improved with text information, which is not need in inference stage.
If we develop this idea, we will keep you posted!
